### PR TITLE
run ember-cli-update

### PR DESCRIPTION
**Pull request by chrisgame**
I noticed a deprecation warning for the babel version used when consuming the addon. I figured ember-cli-update was the fastest way to bring everything up to date.

### CODE REVIEW

**Comment by RuslanZavacky** [comment]
@bantic @mixonic can you please take a look? :) Would appreciate a merge on this one! Thank you 🤝

**Comment by bantic** [comment]
@chrisgame This looks great, thank you! Did you (or @RuslanZavacky) have a chance to run this upgraded version in your app without difficulty?

**Comment by RuslanZavacky** [comment]
@bantic We'll re-iterate with @chrisgame on this one hopefully tomorrow, will run our test suit against it and will see if something pops up.

**Comment by chrisgame** [comment]
Hey @bantic 👋 
Yes I can confirm this works without issue in our app.

**Comment by bantic** [comment]
@chrisgame Great, thanks for the confirm, as well as the PR!

**Comment by chrisgame** [comment]
Hey @bantic, no problem. 
Is it possible to tag and release?

**Comment by bantic** [comment]
@chrisgame Published as v0.4.0. thanks!

**Pull request merged**
